Wisky.SkyAdmin.Manage/Wisky.SkyAdmin.Manage/Areas/Admin/Controllers/DayTypeController.cs
using System.Threading.Tasks;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HmsService.Sdk;
using HmsService.ViewModels;
using HmsService.Models;

namespace Wisky.SkyAdmin.Manage.Areas.Admin.Controllers
{
    public class DayTypeController : Controller
    {
        // GET: DayType
        public ActionResult Index(int brandId)
        {
            var dayTypeEditViewModel = new DayTypeEditViewModel();
            dayTypeEditViewModel.WeekDayNames = loadEnum();
            return View("Index", dayTypeEditViewModel);
        }
        public ActionResult Create()
        {
            var dayTypeEditViewModel = new DayTypeEditViewModel();
            dayTypeEditViewModel.WeekDayNames = loadEnum();
            return View("Create", dayTypeEditViewModel);
        }
        public ActionResult Edit()
        {
            return View();
        }

        public JsonResult GetDayType(JQueryDataTableParamModel param)
        {
            try
            {
                var dayTypeApi = new DayTypeApi();
                var dayTypeList = dayTypeApi.GetAll().ToList();

                var count = 0;
                var list = dayTypeList.Select(dayType => new object[]
                {
                    ++count,
                    dayType.Id,
                    dayType.DayTypeName != null ? dayType.DayTypeName: "",
                    dayType.DaysOfTheWeek != null? dayType.DaysOfTheWeek: "",
                    dayType.FromDate != null ? dayType.FromDate.GetValueOrDefault().ToString("dd/MM/yyyy"): "",
                    dayType.ToDate != null ? dayType.ToDate.GetValueOrDefault().ToString("dd/MM/yyyy"): ""
                }).ToList();

                var totalRecord = list.Count();
                return Json(new { sEcho = param.sEcho, iTotalRecords = totalRecord, iTotalDisplayRecords = totalRecord, aaData = list }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return null;
            }

        }

        [HttpPost]
        public async Task<JsonResult> EditDayTypeAsync(String id, String dayTypeName, String daysOfWeek, String dayTypeRate, String fromDate, String toDate)
        {
            bool result = false;
            try
            {
                var dayTypeApi = new DayTypeApi();
                var dayType = await dayTypeApi.GetAsync(Int32.Parse(id));
                dayType.DayTypeName = dayTypeName;
                dayType.DaysOfTheWeek = daysOfWeek;
                if (fromDate != "")
                {
                    var tmpDate = DateTime.ParseExact(fromDate, "dd/MM/yyyy", null);
                    dayType.FromDate = tmpDate;
                }
                if (toDate != "")
                {
                    var tmpDate = DateTime.ParseExact(toDate, "dd/MM/yyyy", null);
                    dayType.ToDate = tmpDate;
                }
                await dayTypeApi.EditAsync(Int32.Parse(id), dayType);
                result = true;
            }
            catch (Exception ex)
            {
                result = false;
            }
            return Json(result);
        }
        [HttpPost]
        public async Task<JsonResult> DeleteDayTypeAsync(String id)
        {
            string[] result = new string[2] { "failed", "failed" };
            try
            {
                var timeModeApi = new TimeModeApi();
                var timeModeList = timeModeApi.GetAll().Where(t => t.DayTypeId == Int32.Parse(id));
                if (timeModeList.Any())
                {
                    result[0] = timeModeList.First().TimeModeName;
                }
                else
                {
                    result[0] = "";
                    var dayTypeApi = new DayTypeApi();
                    var dayType = await dayTypeApi.GetAsync(Int32.Parse(id));
                    if (dayType.IsActive)
                    {
                        dayType.IsActive = false;
                        await dayTypeApi.EditAsync(Int32.Parse(id), dayType);
                        result[1] = "";
                    }
                    else
                    {
                        result[1] = "failed";
                    }
                }
            }
            catch (Exception ex)
            {
                result = new string[2] { "", "failed" };
            }
            return Json(result);
        }
        [HttpPost]
        public async Task<ActionResult> CreateDayTypeAsync(DayTypeEditViewModel editModel)
        {
            try
            {
                editModel.DayTypeViewModel.BrandId = 1;
                editModel.DayTypeViewModel.IsActive = true;
                var dayTypeApi = new DayTypeApi();
                await dayTypeApi.CreateAsync(editModel.DayTypeViewModel);
            }
            catch (Exception ex)
            {

            }
            return RedirectToAction("Index");
        }
        private string[] loadEnum()
        {
            string[] nameList = new string[]
            {
                DaysOfWeekEnum.Monday.DisplayName(),
                DaysOfWeekEnum.Tuesday.DisplayName(),
                DaysOfWeekEnum.Wednesday.DisplayName(),
                DaysOfWeekEnum.Thursday.DisplayName(),
                DaysOfWeekEnum.Friday.DisplayName(),
                DaysOfWeekEnum.Saturday.DisplayName(),
                DaysOfWeekEnum.Sunday.DisplayName()
            };
            return nameList;
        }
    }
}

Wisky.SkyAdmin.Manage/Wisky.SkyAdmin.Manage/Areas/Admin/Controllers/StoreController.cs
using HmsService.Sdk;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Wisky.SkyAdmin.Manage.Areas.Admin.Controllers
{
    public class StoreController : Controller
    {
        // GET: Store
        public ActionResult GetListStore()
        {
            var brandId = 1;
            var storeApi = new StoreApi();
            var listStore = storeApi.GetActiveStoreByBrandId(brandId).ToList();
            var result = listStore.Select(q => new
            {
                storeId = q.Id,
                storeName = q.Name
            });
            return Json(new { listresult = result }, JsonRequestBehavior.AllowGet);
        }

    }
}

Wisky.SkyAdmin.Manage/Wisky.SkyAdmin.Manage/Areas/Admin/Controllers/TimeModeController.cs
using System.Threading.Tasks;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HmsService.Sdk;
using HmsService.ViewModels;
using HmsService.Models;
using HmsService.Models.Entities;

namespace Wisky.SkyAdmin.Manage.Areas.Admin.Controllers
{
    public class TimeModeController : Controller
    {
        // GET: TimeMode
        public ActionResult Index()
        {
            DayTypeApi dayTypeApi = new DayTypeApi();
            var dayTypeList = dayTypeApi.Get().Where(dayType => dayType.IsActive).Select(dayType => new SelectListItem
            {
                Text = dayType.DayTypeName,
                Value = dayType.Id.ToString()
            });
            TimeModeEditViewModel timeModeEditViewModel = new TimeModeEditViewModel()
            {
                AvailableTimeModeList = dayTypeList
            };

            return View("Index", timeModeEditViewModel);
            //return View();
        }

        public ActionResult Create()
        {
            DayTypeApi dayTypeApi = new DayTypeApi();
            var dayTypeList = dayTypeApi.Get().Where(dayType => dayType.IsActive).Select(dayType => new SelectListItem
            {
                Text = dayType.DayTypeName,
                Value = dayType.Id.ToString()
            });
            TimeModeEditViewModel timeModeEditViewModel = new TimeModeEditViewModel()
            {
                AvailableTimeModeList = dayTypeList
            };

            return View("Create", timeModeEditViewModel);
            //return View();
        }


        [HttpPost]
        public async Task<JsonResult> EditTimeModeAsync(String id, String timeModeName, String timeStart, String timeEnd, String durationMin, String durationMax,/* String rateValue,*/ String dayTypeId/*, String priorityId*/)
        {
            bool result = false;
            try
            {
                var timeModeApi = new TimeModeApi();
                var timeMode = await timeModeApi.GetAsync(Int32.Parse(id));
                timeMode.TimeModeName = timeModeName;
                //timeMode.TimeStart = TimeSpan.ParseExact(timeStart, "hh:mm:ss", null);
                timeMode.TimeStart = TimeSpan.Parse(timeStart);
                timeMode.TimeEnd = TimeSpan.Parse(timeEnd);
                timeMode.DurationMin = TimeSpan.Parse(durationMin);
                timeMode.DurationMax = TimeSpan.Parse(durationMax);
                //timeMode.RateValue = Double.Parse(rateValue);
                timeMode.DayTypeId = Int32.Parse(dayTypeId);
                //timeMode.Priority = Int32.Parse(priorityId);
                await timeModeApi.EditAsync(Int32.Parse(id), timeMode);
                result = true;

            }
            catch (Exception ex)
            {
                result = false;
            }
            return Json(result);
        }
        [HttpPost]
        public async Task<JsonResult> DeleteTimeModeAsync(String id)
        {
            bool result = false;
            try
            {
                var timeModeApi = new TimeModeApi();
                var timeMode = await timeModeApi.GetAsync(Int32.Parse(id));
                if (timeMode.IsActive)
                {
                    timeMode.IsActive = false;
                    await timeModeApi.EditAsync(Int32.Parse(id), timeMode);
                    result = true;
                }
                else
                {
                    result = false;
                }
            }
            catch (Exception ex)
            {
                result = false;
            }
            return Json(result);
        }

        [HttpPost]
        public ActionResult CreateTimeMode(TimeModeEditViewModel timeModeEditViewModel)
        {
            try
            {
                timeModeEditViewModel.TimeModeViewModel.IsActive = true;
                timeModeEditViewModel.TimeModeViewModel.Priority = (int)timeModeEditViewModel.TimeModePriorityEnum;
                var timeModeApi = new TimeModeApi();
                //await timeModeApi.CreateAsync(timeModeEditViewModel.TimeModeViewModel);
                timeModeApi.Create(timeModeEditViewModel.TimeModeViewModel);
            }
            catch (Exception ex)
            {
            }
            return RedirectToAction("Index");
        }

        public JsonResult GetTimeMode(HmsService.Models.JQueryDataTableParamModel param)
        {
            try
            {
                var timeModeApi = new TimeModeApi();
                var listTimeMode = timeModeApi.GetAll().ToList();

                var count = 0;
                var wks = listTimeMode.Select(e => new object[]
                {
                ++count,
                e.Id,
                e.TimeModeName!= null ? e.TimeModeName : "",
                e.TimeStart!= null ? e.TimeStart.GetValueOrDefault().ToString(@"hh\:mm") : "",
                e.TimeEnd!= null ? e.TimeEnd.GetValueOrDefault().ToString(@"hh\:mm") : "",
                e.DurationMin != null ? e.DurationMin.GetValueOrDefault().ToString(@"hh\:mm"): "",
                e.DurationMax != null ? e.DurationMax.GetValueOrDefault().ToString(@"hh\:mm"): "",
                //e.RateValue !=null ? e.RateValue :0,
                e.DayTypeId,
                e.DayType.DayTypeName,
                //((PriorityEnum)e.Priority),
                //((PriorityEnum)e.Priority).DisplayName(),
                }).ToList();

                var totalRecords = wks.Count();
                return Json(new
                {
                    sEcho = param.sEcho,
                    iTotalRecords = totalRecords,
                    iTotalDisplayRecords = totalRecords,
                    aaData = wks
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return null;
            }
        }

    }
}

Wisky.SkyAdmin.Manage/Wisky.SkyAdmin.Manage/Views/Shared/NotFound.cshtml
<!--A Design by W3layouts
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
@{ 
    Layout = null;
}

<!DOCTYPE HTMl>
<html>
<head>
<title>404</title>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<link rel="stylesheet" href="~/Content/errorpage/css/style.css" type="text/css" media="all" />
<link href='http://fonts.googleapis.com/css?family=Strait' rel='stylesheet' type='text/css'>
</head>
<body>
	
			<div class="wrap">
				<div class="banner"><img src="~/Content/errorpage/image/404-2.png" alt="" /></div>
				<div class="search">
					<div class='crt-btn'><a href='@Url.Action("Login","Account")'>Homepage</a></div>
				</div>
			</div>
	    	
</body>
</html>    

Wisky.SkyAdmin.Manage/Wisky.SkyAdmin.Manage/Views/Shared/_Constant.cshtml
<script>
    window.urls = {
        "Product_GetStoreList": "@(Url.Action("GetStoreList", "Product"))",
        "Delivery_Create": "@(Url.Action("Create","Delivery",new { area = "Delivery" }))",
        "Delivery_LoadAllCustomer": "@(Url.Action("LoadAllCustomer","Delivery", new { area="Delivery"}))",
        "Delivery_GetCustomerDetail": "@(Url.Action("GetCustomerDetail","Delivery", new { area="Delivery"}))",
        "Delivery_LoadItemByCategory": "@(Url.Action("LoadItemByCategory","Delivery",new { area="Delivery"}))",
        "Product_UpdateAssignToStore": "@(Url.Action("UpdateAssignToStore", "Product", new { area="Admin"}))",
        "Customer_Order_History":"@(Url.Action("GetCustomerProductData", "Customer", new {area="Customer"}))",

    }
</script>

Wisky.SkyAdmin.Manage/Wisky.SkyAdmin.Manage/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>

    <link rel='shortcut icon' type='image/x-icon' href='/Content/images/favicon.ico' />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @Utils.GetCurrentDateTime().Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Wisky.SkyAdmin.Manage/Wisky.SkyAdmin.Manage/Views/Shared/_MenuForManagers.cshtml
@using HmsService.ViewModels;
@model List<MenuViewModel>

@ShowAllMenuItem(Model)

@helper CheckLastItem(int menuIndex, IEnumerable<MenuViewModel> listItem, MenuViewModel lastItem)
    {
        if (menuIndex == listItem.Count() - 2)
        {
            string lastItemLink = Url.Action(lastItem.Action.Trim(), lastItem.Controller.Trim(), new { area = lastItem.Area.Trim() });
            <li>
                <a href="@lastItemLink"><i class="@lastItem.IconCss"></i> @lastItem.MenuText</a>
            </li>
        }
}


@helper ShowAllMenuItem(List<MenuViewModel> menus)
    {
        /**/

        for (var i = 0; i < menus.Count - 1; i++)
        {
            var item = menus.ElementAt(i);
            var nextItem = menus.ElementAt(i + 1);
            string sMenuClass = nextItem.ParentMenuId == item.Id ? "sub-menu" : "";
            string itemLink = nextItem.ParentMenuId == item.Id ? "#" : Url.Action(item.Action.Trim(), item.Controller.Trim(), new { area = item.Area.Trim() });

            if (nextItem.MenuLevel == item.MenuLevel)
            {
                <li>
                    <a href="@itemLink"><i class="@item.IconCss"></i> @item.MenuText</a>
                </li>
            }
            else
            {
                if (nextItem.MenuLevel > item.MenuLevel)
                {
                    @Html.Raw("<li class='" + sMenuClass + "'>");
                    <a href="@itemLink"><i class="@item.IconCss"></i> @item.MenuText</a>
                    @Html.Raw("<ul>");
                }
                else
                {
                    <li>
                        <a href="@itemLink"><i class="@item.IconCss"></i> @item.MenuText</a>
                    </li>
                    var k = item.MenuLevel - nextItem.MenuLevel;
                    for (var j = 0; j < k; j++)
                    {
                        @Html.Raw("</ul></li>");
                    }
                }
            }
            @CheckLastItem(i, menus, nextItem);
        }
}

Wisky.SkyAdmin.Manage/Wisky.SkyAdmin.Manage/Views/Shared/_MenuForStore.cshtml
@using HmsService.ViewModels;
@using Wisky.SkyAdmin.Manage.Controllers;
@{
    var user = HttpContext.Current.User;
    var currentStore = HmsService.Models.Utils.GetStore();
    //var storeId = ViewBag.storeId as string;
    var storeName = ViewBag.storeName as string;
    //var brandId = HmsService.Models.Utils.GetBrandId();
}

@if ((user.IsInRole("BrandManager") || user.IsInRole("StoreManager")))
{
    <li id="menuQuanLyNhanVienCuaHang">
        @*<a href="@Url.Action("Index","StoreManager", new { brandId = brandId, storeId = storeId, storeName = storeName, area= "Admin" })"><i class="zmdi zmdi-accounts"></i> Quản lý tài khoản nhân viên</a>*@
    </li>
    <li class="sub-menu" id="menuChamCong">
        <a href="#"><i class="sub-menu zmdi zmdi-file-add"></i> Quản lý</a>
        <ul>
            <li class="submenu-style" id="subMenuQuanLyNhanVien"><a href="#"><i class="zmdi zmdi-account"></i> Quản lý nhân viên cửa hàng</a></li>
            <li class="submenu-style" id="subMenuQuanLyLoaiNgay"><a href="@Url.Action("Index","DayType", new { area= "Admin"  })"><i class="zmdi zmdi-aspect-ratio-alt"></i> Quản lý loại ngày</a></li>
            <li class="submenu-style" id="subMenuQuanLyTimeMode"><a href="@Url.Action("Index","TimeMode", new {area= "Admin" })"><i class="zmdi zmdi-aspect-ratio-alt"></i> Quản lý timemode</a></li>
            <li class="submenu-style" id="subMenuQuanLyCaMau"><a href="@Url.Action("Index","WorkingShift", new {  area= "Admin" })"><i class="zmdi zmdi-aspect-ratio-alt"></i> Quản lý ca mẫu</a></li>
            <li class="submenu-style" id="subMenuQuanLyChamCong"><a href="@Url.Action("Index","Attendance", new { area= "Admin" })"><i class="zmdi zmdi-aspect-ratio-alt"></i> Duyệt chấm công</a></li>
            <li class="submenu-style" id="subMenuQuanLyPhanCong"><a href="@Url.Action("Job2","Attendance", new { area= "Admin" })"><i class="zmdi zmdi-aspect-ratio-alt"></i> Phân công </a></li>
        </ul>
    </li>
}


<style>
    .sub-menu ul > li ul {
        margin: 0px !important;
    }

    .sub-menu .sub-menu:first-child > a:before, .sub-menu:first-child > a:after {
        top: 11px;
    }
</style>
<script>
    $(document).ready(function () {
        @if (Model != null)
        {
            for(int i = 0; i < Model.Count(); i++)
            {
                if (Model[i].enable == false)
                {
                    <text>
        if (document.getElementById("@Model[i].name") != null) {
            document.getElementById("@Model[i].name").setAttribute("hidden", "true");
        }

        </text>
                }
            }
        }

    });
</script>

Wisky.SkyAdmin.Manage/Wisky.SkyAdmin.Manage/Views/Shared/_MenuForSysAdmin.cshtml
@using HmsService.ViewModels;
@{
    var user = HttpContext.Current.User;
}


<li>
    <a href="@Url.Action("Index","Brand", new { area= "SysAdmin" })"><i class="zmdi zmdi-coffee"></i> Quản lí Thương Hiệu</a>
</li>
<li>
    <a href="@Url.Action("Index","Store", new { area= "SysAdmin" })"><i class="zmdi zmdi-coffee"></i> Danh sách cửa hàng</a>
</li>
<li>
    <a href="@Url.Action("Index","SysAccount", new { area= "SysAdmin" })"><i class="zmdi zmdi-account"></i> Quản lí Tài Khoản</a>
</li>
<li>
    <a href="@Url.Action("Index","Theme", new { area = "SysAdmin"  })"><i class="zmdi zmdi-account"></i> Quản lí Theme</a>
</li>
<li>
    <a href="@Url.Action("Index","ReDateReport", new { area = "SysAdmin"  })"><i class="zmdi zmdi-account"></i> Quản lý Báo cáo</a>
</li>
<li>
    <a href="@Url.Action("Index","PosFile", new { area = "SysAdmin"  })"><i class="zmdi zmdi-account"></i> Quản lý POS file</a>
</li>
<li>
    <a href="@Url.Action("Index","Order", new { area = "SysAdmin"  })"><i class="zmdi zmdi-mood"></i> Quản lý Order</a>
</li>
<li>
    <a href="@Url.Action("ConfigMenuBrand","MenuConfig", new { area = "SysAdmin"  })"><i class="zmdi zmdi-account"></i> Quản lý menu Brand</a>
</li>
<li>
    <a href="@Url.Action("ConfigMenuStore","MenuConfig", new { area = "SysAdmin"  })"><i class="zmdi zmdi-account"></i> Quản lý menu Store</a>
</li>