Wisky.SkyAdmin.Manage/Wisky.SkyAdmin.Manage/Areas/Admin/Controllers/WorkingShiftController.cs
using HmsService.Models;
using HmsService.Models.Entities;
using HmsService.Sdk;
using HmsService.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Wisky.SkyAdmin.Manage.Areas.Admin.Controllers
{
  // GET: Admin/WorkingShift
        public class WorkingShiftController : Controller
        {
            HmsEntities entities = new HmsEntities();
            // GET: WorkingShift
            public ActionResult Index()
            {
                BrandApi brandApi = new BrandApi();
                var wksList = brandApi.Get().Select(c => new SelectListItem
                {
                    Text = c.BrandName,
                    Value = c.Id.ToString(),
                });

                WorkingShiftEditViewModel wksEditViewModel = new WorkingShiftEditViewModel()
                {
                    AvailableBrand = wksList,

                };
                return View("Index", wksEditViewModel);

            }
            public ActionResult Create()
            {
                BrandApi brandApi = new BrandApi();
                var wksList = brandApi.Get().Select(c => new SelectListItem
                {
                    Text = c.BrandName,
                    Value = c.Id.ToString(),
                });

                WorkingShiftEditViewModel wksEditViewModel = new WorkingShiftEditViewModel()
                {
                    AvailableBrand = wksList,

                };
                return View("Create", wksEditViewModel);

            }
            public ActionResult CreateWorkingShift(WorkingShiftEditViewModel wks)
            {
                try
                {
                    WorkingShiftApi wksApi = new WorkingShiftApi();
                    wks.WorkingShiftViewModel.IsActive = true;
                    wks.WorkingShiftViewModel.WorkingShiftType = (int)wks.WorkingShiftTypeSelected;
                    wksApi.Create(wks.WorkingShiftViewModel);
                }
                catch (Exception e)
                {
                }
                return RedirectToAction("Index");
            }

            public JsonResult GetWorkingShifts()
            {
                try
                {
                    var workingShiftApi = new WorkingShiftApi();
                    var listWorkingShift = workingShiftApi.GetAll().ToList();

                    var count = 0;
                    //var wks = listWorkingShift.Select(e => new object[]
                    //{
                    //e.Id,
                    //e.Brand.BrandName,
                    //e.WorkingShiftName!= null ? e.WorkingShiftName : "",
                    //e.ShiftMin!= null ? e.ShiftMin.GetValueOrDefault().ToString(@"hh\:mm") : "",
                    //e.ShiftMax!= null ? e.ShiftMax.GetValueOrDefault().ToString(@"hh\:mm") : "",
                    //e.FromDate!= null ? e.FromDate.GetValueOrDefault().ToShortDateString() : "",
                    //e.ToDate!= null ? e.ToDate.GetValueOrDefault().ToShortDateString() : "",
                    //e.ExpandTime !=null ? e.ExpandTime.GetValueOrDefault().ToString(@"hh\:mm"):"",
                    //e.BrandId,
                    //}).ToList();

                    var wks = listWorkingShift.Select(e => new WorkingShiftEditViewModel2
                    {
                        Id = e.Id,
                        BrandId = e.Brand.Id,
                        WorkingShiftName = e.WorkingShiftName != null ? e.WorkingShiftName : "",
                        ShiftMin = e.ShiftMin.GetValueOrDefault(),
                        ShiftMax = e.ShiftMax.GetValueOrDefault(),
                        ExpandTime = e.ExpandTime.GetValueOrDefault(),
                    }).ToList();


                    var totalRecords = wks.Count();
                    return Json(new
                    {
                        aaData = wks
                    }, JsonRequestBehavior.AllowGet);
                }
                catch (Exception e)
                {
                    return null;
                }
            }

            public JsonResult GetWorkingShift(HmsService.Models.JQueryDataTableParamModel param)
            {
                try
                {
                    var workingShiftApi = new WorkingShiftApi();
                    var listWorkingShift = workingShiftApi.GetAll().ToList();

                    var count = 0;
                    var wks = listWorkingShift.Select(e => new object[]
                    {
                ++count, //0
                e.Id, //1
                e.Brand.BrandName, //2
                e.WorkingShiftName!= null ? e.WorkingShiftName : "", //3
                e.ShiftMin!= null ? e.ShiftMin.GetValueOrDefault().ToString(@"hh\:mm") : "", //4
                e.ShiftMax!= null ? e.ShiftMax.GetValueOrDefault().ToString(@"hh\:mm") : "", //5
                ((WorkingShiftTypeEnum)e.WorkingShiftType).DisplayName(), //6
                e.ExpandTime !=null ? e.ExpandTime.GetValueOrDefault().ToString(@"hh\:mm"):"", //7
                e.BrandId,  //8
                e.WorkingShiftType,//9
                    }).ToList();

                    var totalRecords = wks.Count();
                    return Json(new
                    {
                        sEcho = param.sEcho,
                        iTotalRecords = totalRecords,
                        iTotalDisplayRecords = totalRecords,
                        aaData = wks
                    }, JsonRequestBehavior.AllowGet);
                }
                catch (Exception e)
                {
                    return null;
                }
            }

            [HttpPost]
            public async Task<JsonResult> EditWorkingShift(int Id, int brandId, string name, string shiftMin, string shiftMax, int wksType, string hour)
            {
                bool result = false;
                try
                {
                    var wksApi = new WorkingShiftApi();
                    var wks = await wksApi.GetAsync(Id);
                    wks.BrandId = brandId;
                    wks.WorkingShiftName = name;
                    wks.ShiftMin = TimeSpan.Parse(shiftMin);
                    wks.ShiftMax = TimeSpan.Parse(shiftMax);
                    wks.WorkingShiftType = wksType;
                    wks.ExpandTime = TimeSpan.Parse(hour);
                    await wksApi.EditAsync(Id, wks);
                    result = true;
                }
                catch (Exception e)
                {
                    result = false;
                }
                return Json(result);
            }
            [HttpPost]
            public async Task<JsonResult> DeleteWorkingShift(int? Id)
            {
                try
                {
                    var wksApi = new WorkingShiftApi();
                    var model = await wksApi.GetAsync(Id);
                    if (model == null || !model.IsActive)
                    {
                        return Json(new { success = false });
                    }
                    model.IsActive = false;
                    await wksApi.EditAsync(model.Id, model);
                    return Json(new { success = true });
                }
                catch (System.Exception e)
                {
                    return Json(new { success = false });
                }
            }
            [ValidateAntiForgeryToken]
            public ActionResult Edit([Bind(Include = "Id,WorkingShiftName,ShiftMin,ShiftMax,ExpectedHoursWork")] WorkTypeViewModel wks)
            {
                if (ModelState.IsValid)
                {
                    entities.Entry(wks).State = EntityState.Modified;
                    entities.SaveChanges();

                    string url = Url.Action("Index", "Addresses", new { id = wks.Id });
                    return Json(new { success = true, url = url });
                }


                return PartialView("_Edit", wks);
            }
        }
    public class WorkingShiftEditViewModel2
    {
        public virtual int Id { get; set; }
        public virtual Nullable<int> BrandId { get; set; }
        public virtual string WorkingShiftName { get; set; }
        public virtual Nullable<int> WorkingShiftType { get; set; }
        public virtual Nullable<System.TimeSpan> ShiftMin { get; set; }
        public virtual Nullable<System.TimeSpan> ShiftMax { get; set; }
        public virtual string FromDate { get; set; }
        public virtual string ToDate { get; set; }
        public virtual Nullable<System.TimeSpan> ExpandTime { get; set; }
    }
}
   

Wisky.SkyAdmin.Manage/Wisky.SkyAdmin.Manage/Areas/Admin/Views/WorkingShift/Create.cshtml
@using HmsService.ViewModels;
@using HmsService.Models;
@model WorkingShiftEditViewModel
@{
    ViewBag.Title = "Create";
}
@using (Html.BeginForm("CreateWorkingShift", "WorkingShift"))

{
    <div class="card" style="width:50%;margin:0 auto">
        <div class="card-header">
            <span>Tạo ca mẫu</span>

        </div>
        <div class="card-body">
            <form action="" method="post" class="form-horizontal">
                <div class="form-group row">
                    <label class="col-md-4 col-form-label" for="hf-email">Quản lý</label>
                    <div class="col-md-8">
                        @Html.DropDownListFor(wks => wks.WorkingShiftViewModel.BrandId, Model.AvailableBrand, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-4 col-form-label" for="hf-email">Tên ca mẫu</label>
                    <div class="col-md-8">
                        @Html.TextBoxFor(wks => wks.WorkingShiftViewModel.WorkingShiftName, new { @class = "form-control", required = "required" })
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-4 col-form-label" for="hf-email">Thời gian bắt đâu ca</label>
                    <div class="col-md-8">
                        @Html.TextBoxFor(emp => emp.WorkingShiftViewModel.ShiftMin, new { @class = "form-control", @required = "required", id = "shiftMin", onchange = "checktime(1)" })
                        <lablel class="alert-danger" style="display:none" id="fromTimeAlert"></lablel>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-4 col-form-label" for="hf-email">Thời gian kết thúc ca</label>
                    <div class="col-md-8">
                        @Html.TextBoxFor(emp => emp.WorkingShiftViewModel.ShiftMax, new { @class = "form-control", @required = "required", id = "shiftMax", onchange = "checktime(2)" })
                        <lablel class="alert-danger" style="display:none" id="toTimeAlert"></lablel>
                    </div>
                </div>
                @*<div class="form-group row">
                    <label class="col-md-4 col-form-label" for="hf-email">Ngày bắt đầu</label>
                    <div class="col-md-8 form_date date input-append" data-date="" data-date-format="dd/mm/yyyy" data-link-field="dateTimePicker" data-link-format="dd/mm/yyyy">
                        @Html.TextBoxFor(emp => emp.WorkingShiftViewModel.FromDate, new { @class = "form-control", @required = "required", @readonly = "true", id = "fromDate" })
                        <lablel class="alert-danger" style="display:none" id="fromDateAlert"></lablel>
                        <span class="add-on"><i class="icon-remove" style="display:none"></i></span>
                        <span class="add-on"><i class="icon-th" style="display:none"></i></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-4 col-form-label" for="hf-email">Ngày kết thúc</label>
                    <div class="col-md-8 form_date date input-append" data-date="" data-date-format="dd/mm/yyyy" data-link-field="dateTimePicker" data-link-format="dd/mm/yyyy">
                        @Html.TextBoxFor(emp => emp.WorkingShiftViewModel.ToDate, new { @class = "form-control", @required = "required", @readonly = "true", id = "toDate" })
                        <lablel class="alert-danger" style="display:none" id="toDateAlert"></lablel>
                        <span class="add-on"><i class="icon-remove" style="display:none"></i></span>
                        <span class="add-on"><i class="icon-th" style="display:none"></i></span>
                    </div>
                </div>*@
                <div class="form-group row">
                    <label class="col-md-4 col-form-label" for="hf-email">Loại ca mẫu</label>
                    <div class="col-md-8">
                        @Html.EnumDropDownListFor(emp => emp.WorkingShiftTypeSelected, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-4 col-form-label" for="hf-email">Thời gian làm thêm</label>
                    <div class="col-md-8">
                        @Html.TextBoxFor(emp => emp.WorkingShiftViewModel.ExpandTime, new { @class = "form-control", @required = "required", id = "expandTime" })
                    </div>
                </div>

                @*<input type="text" id="timepicker" />*@

            </form>
        </div>
        <div class="card-footer">
            <button type="reset" class="btn btn-sm btn-danger pull-right" style="margin-left:5px">
                <i class="fa fa-refresh"></i> Làm lại
            </button>
            <button type="submit" class="btn btn-sm btn-primary pull-right">
                <i class="fa fa-floppy-o"></i> Tạo ca mẫu
            </button>

        </div>
    </div>
}

<script>

    $('.form_date').datetimepicker({
        language: 'vi',
        weekStart: 1,
        todayBtn: 1,
        autoclose: 1,
        todayHighlight: 1,
        startView: 2,
        minView: 2,
        forceParse: 0
    });
    $(document).ready(function () {
        $('#shiftMin').mdtimepicker({
            timeFormat: 'hh:mm:ss.000',
            format: 'hh:mm:ss',
            theme: 'indigo',
            readOnly: true,
            hourPadding: false
        });
        $('#shiftMax').mdtimepicker({
            timeFormat: 'hh:mm:ss.000',
            format: 'hh:mm:ss',
            theme: 'indigo',
            readOnly: true,
            hourPadding: false
        });
        $('#expandTime').mdtimepicker({
            timeFormat: 'hh:mm:ss.000',
            format: 'hh:mm:ss',
            theme: 'indigo',
            readOnly: true,
            hourPadding: false
        });

    });

    $(function () {
        $("#toDate").change(function () {
            checkDate(2);
        });
        $("#fromDate").change(function () {
            checkDate(1);
        });
        $("#shiftMin").change(function () {
            checktime(1);
        });
        $("#shiftMax").change(function () {
            checktime(2);
        });
    });
    function checktime(value) {
        var startTime = $("#shiftMin").val();
        var endTime = $("#shiftMax").val();
        var regExp = /(\d{1,2})\:(\d{1,2})/;
        if (parseInt(endTime.replace(regExp, "$1$2")) < parseInt(startTime.replace(regExp, "$1$2"))) {
            if (value == 1) {
                $("#shiftMin").val(null);
                $('#fromTimeAlert').text("Xin hãy chọn lại thời gian").show('fast');
                $(':input[type="submit"]').prop('disabled', true);
            } else {
                $("#shiftMax").val(null);
                $(':input[type="submit"]').prop('disabled', true);
                $('#toTimeAlert').text("Xin hãy chọn lại thời gian").show('fast');
            }
        } else {
            $(':input[type="submit"]').prop('disabled', false);
            $('#toTimeAlert').hide();
            $('#fromTimeAlert').hide();
        }
    }
    function checkDate(value) {
        var fromDateValue = $("#fromDate").val();
        var toDateValue = $("#toDate").val();
        if (fromDateValue != 'NULL' && toDateValue != 'NULL') {
            fromDateValue = fromDateValue.split('/');
            toDateValue = toDateValue.split('/');

            var tmpFromDate = new Date(fromDateValue[2], fromDateValue[1] - 1, fromDateValue[0]);
            var tmpToDate = new Date(toDateValue[2], toDateValue[1] - 1, toDateValue[0]);
            if (tmpToDate < tmpFromDate) {
                if (value == 1) {
                    $("#fromDate").val(null);
                    $('#fromDateAlert').text("Xin hãy chọn lại ngày").show('fast');
                    $(':input[type="submit"]').prop('disabled', true);
                } else {
                    $("#toDate").val(null);
                    $('#toDateAlert').text("Xin hãy chọn lại ngày").show('fast');
                    $(':input[type="submit"]').prop('disabled', true);
                }
            } else {
                $(':input[type="submit"]').prop('disabled', false);
                $('#toDateAlert').hide();
                $('#fromDateAlert').hide();
            }
        }
    }
    //$('.form_time').datetimepicker({
    //    language: 'en',
    //    weekStart: 1,
    //    todayBtn: 1,
    //    autoclose: 1,
    //    todayHighlight: 1,
    //    startView: 1,
    //    minView: 0,
    //    maxView: 1,
    //    forceParse: 0
    //});

</script>

Wisky.SkyAdmin.Manage/Wisky.SkyAdmin.Manage/Areas/Admin/Views/WorkingShift/Editor.cshtml
@using HmsService.ViewModels;
@using HmsService.Models;
@model WorkingShiftEditViewModel
@{
    ViewBag.Title = "Editor";
}
@using (Html.BeginForm("Create", "WorkingShift"))

{
    <div class="card" style="width:50%;margin:0 auto">
        <div class="card-header">
            <strong>Tạo ca mẫu</strong>

        </div>
        <div class="card-body">
            <form action="" method="post" class="form-horizontal">
                <div class="form-group row">
                    <label class="col-md-4 col-form-label" for="hf-email">Quản lý</label>
                    <div class="col-md-8">
                        @Html.DropDownListFor(wks => wks.WorkingShiftViewModel.BrandId, Model.AvailableBrand, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-4 col-form-label" for="hf-email">Tên ca mẫu</label>
                    <div class="col-md-8">
                        @Html.TextBoxFor(wks => wks.WorkingShiftViewModel.WorkingShiftName, new { @class = "form-control", required = "required" })
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-4 col-form-label" for="hf-email">Thời gian bắt đâu ca</label>
                    <div class="col-md-8">
                        @Html.TextBoxFor(emp => emp.WorkingShiftViewModel.ShiftMin, new { @class = "form-control", @required = "required", id = "shiftMin", onchange = "checktime(1)" })
                        <lablel class="alert-danger" style="display:none" id="fromTimeAlert"></lablel>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-4 col-form-label" for="hf-email">Thời gian kết thúc ca</label>
                    <div class="col-md-8">
                        @Html.TextBoxFor(emp => emp.WorkingShiftViewModel.ShiftMax, new { @class = "form-control", @required = "required", id = "shiftMax" , onchange = "checktime(2)" })
                       <lablel class="alert-danger" style="display:none" id="toTimeAlert"></lablel>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-4 col-form-label" for="hf-email">Ngày bắt đầu</label>
                    <div class="col-md-8 form_date date input-append" data-date="" data-date-format="dd/mm/yyyy" data-link-field="dateTimePicker" data-link-format="dd/mm/yyyy">
                        @Html.TextBoxFor(emp => emp.WorkingShiftViewModel.FromDate, new { @class = "form-control", @required = "required", @readonly = "true",id="fromDate" })
                        <lablel class="alert-danger" style="display:none" id="fromDateAlert"></lablel>
                        <span class="add-on"><i class="icon-remove" style="display:none"></i></span>
                        <span class="add-on"><i class="icon-th" style="display:none"></i></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-4 col-form-label" for="hf-email">Ngày kết thúc</label>
                    <div class="col-md-8 form_date date input-append" data-date="" data-date-format="dd/mm/yyyy" data-link-field="dateTimePicker" data-link-format="dd/mm/yyyy">
                        @Html.TextBoxFor(emp => emp.WorkingShiftViewModel.ToDate, new { @class = "form-control", @required = "required", @readonly = "true" ,id="toDate"})
                        <lablel class="alert-danger" style="display:none" id="toDateAlert"></lablel>
                        <span class="add-on"><i class="icon-remove" style="display:none"></i></span>
                        <span class="add-on"><i class="icon-th" style="display:none"></i></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-4 col-form-label" for="hf-email">Loại ca mẫu</label>
                    <div class="col-md-8">
                        @Html.EnumDropDownListFor(emp => emp.WorkingShiftTypeSelected, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-md-4 col-form-label" for="hf-email">Thời gian làm thêm</label>
                    <div class="col-md-8">
                        @Html.TextBoxFor(emp => emp.WorkingShiftViewModel.ExpandTime, new { @class = "form-control", @required = "required", id = "expandTime" })
                    </div>
                </div>

                @*<input type="text" id="timepicker" />*@

            </form>
        </div>
        <div class="card-footer">
            <button type="reset" class="btn btn-sm btn-danger pull-right" style="margin-left:5px">
                <i class="fa fa-refresh"></i> Làm lại
            </button>
            <button type="submit" class="btn btn-sm btn-primary pull-right">
                <i class="fa fa-floppy-o"></i> Tạo ca mẫu
            </button>

        </div>
    </div>
}

<script>

    $('.form_date').datetimepicker({
        language: 'vi',
        weekStart: 1,
        todayBtn: 1,
        autoclose: 1,
        todayHighlight: 1,
        startView: 2,
        minView: 2,
        forceParse: 0
    });
    $(document).ready(function () {
        $('#shiftMin').mdtimepicker({
            timeFormat: 'hh:mm:ss.000',
            format: 'hh:mm:ss',
            theme: 'indigo',
            readOnly: true,
            hourPadding: false
        });
        $('#shiftMax').mdtimepicker({
            timeFormat: 'hh:mm:ss.000',
            format: 'hh:mm:ss',
            theme: 'indigo',
            readOnly: true,
            hourPadding: false
        });
        $('#expandTime').mdtimepicker({
            timeFormat: 'hh:mm:ss.000',
            format: 'hh:mm:ss',
            theme: 'indigo',
            readOnly: true,
            hourPadding: false
        });

    });

    $(function () {
        $("#toDate").change(function () {
            checkDate(2);
        });
        $("#fromDate").change(function () {
            checkDate(1);
        });
        $("#shiftMin").change(function () {
            checktime(1);
        });
        $("#shiftMax").change(function () {
            checktime(2);
        });
    });
    function checktime(value) {
        var startTime = $("#shiftMin").val();
        var endTime = $("#shiftMax").val();
        var regExp = /(\d{1,2})\:(\d{1,2})/;
        if (parseInt(endTime.replace(regExp, "$1$2")) < parseInt(startTime.replace(regExp, "$1$2"))) {
            if (value == 1) {
                $("#shiftMin").val(null);
                $('#fromTimeAlert').text("Xin hãy nhập time").show('fast');
            } else {
                $("#shiftMax").val(null);
                $('#toTimeAlert').text("Xin hãy nhập time").show('fast');
            }
        } else {
            $('#toTimeAlert').hide();
            $('#fromTimeAlert').hide();
        }
    }
    function checkDate(value) {
        var fromDateValue = $("#fromDate").val();
        var toDateValue = $("#toDate").val();
        if (fromDateValue != 'NULL' && toDateValue != 'NULL') {
            fromDateValue = fromDateValue.split('/');
            toDateValue = toDateValue.split('/');

            var tmpFromDate = new Date(fromDateValue[2], fromDateValue[1] - 1, fromDateValue[0]);
            var tmpToDate = new Date(toDateValue[2], toDateValue[1] - 1, toDateValue[0]);
            if (tmpToDate < tmpFromDate) {
                if (value == 1) {
                    $("#fromDate").val(null);
                    $('#fromDateAlert').text("Xin hãy nhập 'Đến Ngày' sau 'Từ Ngày'").show('fast');
                } else {
                    $("#toDate").val(null);
                    $('#toDateAlert').text("Xin hãy nhập 'Đến Ngày' sau 'Từ Ngày'").show('fast');
                }
            } else {
                $('#toDateAlert').hide();
                $('#fromDateAlert').hide();
            }
        }
    }
    //$('.form_time').datetimepicker({
    //    language: 'en',
    //    weekStart: 1,
    //    todayBtn: 1,
    //    autoclose: 1,
    //    todayHighlight: 1,
    //    startView: 1,
    //    minView: 0,
    //    maxView: 1,
    //    forceParse: 0
    //});

</script>